"""empty message

Revision ID: 3b2cacd494cb
Revises: 5811af4990cd
Create Date: 2017-03-17 11:12:20.835000

"""

# revision identifiers, used by Alembic.
revision = '3b2cacd494cb'
down_revision = '5811af4990cd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'parent_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
