"""empty message

Revision ID: a3349570b96a
Revises: None
Create Date: 2017-04-01 15:07:00.028000

"""

# revision identifiers, used by Alembic.
revision = 'a3349570b96a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('course_apply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('success_case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('tag', sa.String(length=10), nullable=True),
    sa.Column('background', sa.String(length=1000), nullable=True),
    sa.Column('strategy', sa.String(length=1000), nullable=True),
    sa.Column('experience', sa.String(length=1000), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('password', sa.String(length=48), nullable=True),
    sa.Column('chinese_name', sa.String(length=20), nullable=True),
    sa.Column('english_name', sa.String(length=20), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('verify_token', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('role_user_relationship',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('student_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sexual', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=10), nullable=True),
    sa.Column('age', sa.String(length=5), nullable=True),
    sa.Column('school', sa.String(length=20), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('study_country', sa.String(length=10), nullable=True),
    sa.Column('enrollment_time', sa.String(length=10), nullable=True),
    sa.Column('major', sa.String(length=20), nullable=True),
    sa.Column('course_name', sa.String(length=20), nullable=True),
    sa.Column('learn_range', sa.String(length=40), nullable=True),
    sa.Column('weichat', sa.String(length=20), nullable=True),
    sa.Column('parent_phone', sa.String(length=16), nullable=True),
    sa.Column('remark', sa.String(length=100), nullable=True),
    sa.Column('test1', sa.String(length=20), nullable=True),
    sa.Column('score1', sa.String(length=10), nullable=True),
    sa.Column('test2', sa.String(length=20), nullable=True),
    sa.Column('score2', sa.String(length=10), nullable=True),
    sa.Column('test3', sa.String(length=20), nullable=True),
    sa.Column('score3', sa.String(length=10), nullable=True),
    sa.Column('test4', sa.String(length=20), nullable=True),
    sa.Column('score4', sa.String(length=10), nullable=True),
    sa.Column('test5', sa.String(length=20), nullable=True),
    sa.Column('score5', sa.String(length=10), nullable=True),
    sa.Column('admission_school', sa.String(length=20), nullable=True),
    sa.Column('admission_major', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('teacher_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('graduated', sa.String(length=20), nullable=True),
    sa.Column('major', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('weichat', sa.String(length=20), nullable=True),
    sa.Column('introduce', sa.String(length=200), nullable=True),
    sa.Column('success_case', sa.String(length=200), nullable=True),
    sa.Column('feature', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('course_talbe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('stop_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_info.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_info.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8',
    mysql_engine='InnoDB'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_talbe')
    op.drop_table('teacher_info')
    op.drop_table('student_info')
    op.drop_table('role_user_relationship')
    op.drop_table('user')
    op.drop_table('success_case')
    op.drop_table('role')
    op.drop_table('course_apply')
    op.drop_table('course')
    ### end Alembic commands ###
